/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#define RCC_AHB1ENR   (*(volatile uint32_t*)0x40023830)
#define GPIOA_MODER   (*(volatile uint32_t*)0x40020000)
#define GPIOA_ODR    (*(volatile uint32_t*)0x40020014)

#define SysTick_BASE  (*(volatile uint32_t*)0xE000E010)
#define SYST_CSR      (*(volatile uint32_t*)0xE000E010)
#define SYST_RVR      (*(volatile uint32_t*)0xE000E014)
#define SYST_CVR      (*(volatile uint32_t*)0xE000E018)


volatile uint32_t gtick = 0;


void SysTick_Handler(void){
	gtick++;
}
int main(void){
	RCC_AHB1ENR|=(1<<0);
	GPIOA_MODER &= ~(3<<10);
	GPIOA_MODER|=(1<<10);



	SYST_RVR = 16000 - 1;//reload value
	SYST_CVR = 0; //current count
	SYST_CSR = 0x07;//enable systick and clk timer use 111




while(1){
	led_task();
  }
}
void delay(){
	for(int i=0;i<=20000;i++);
}


void led_task(void){
	static uint32_t end =0;

	if(gtick-end>=1000){

		GPIOA_ODR|=(1<<5);

		delay();

		GPIOA_ODR &=~(1<<5);

		delay();

		end=gtick;

	}
}
