/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>


#define RCC_AHB1ENR   (*(volatile uint32_t*)0x40023830)
#define RCC_APB1ENR   (*(volatile uint32_t*)0x40023840)
#define RCC_APB2ENR   (*(volatile uint32_t*)0x40023844)


#define GPIOA_MODER   (*(volatile uint32_t*)0x40020000)
#define GPIOA_AFRL    (*(volatile uint32_t*)0x40020020)
#define GPIOA_AFRH    (*(volatile uint32_t*)0x40020024)


#define USART1_SR     (*(volatile uint32_t*)0x40011000)
#define USART1_DR     (*(volatile uint32_t*)0x40011004)
#define USART1_BRR    (*(volatile uint32_t*)0x40011008)
#define USART1_CR1    (*(volatile uint32_t*)0x4001100C)


#define USART2_SR     (*(volatile uint32_t*)0x40004400)
#define USART2_DR     (*(volatile uint32_t*)0x40004404)
#define USART2_BRR    (*(volatile uint32_t*)0x40004408)
#define USART2_CR1    (*(volatile uint32_t*)0x4000440C)


void delay_ms(volatile uint32_t count)
{
    while(count--)
    {
        volatile uint32_t i;

        for(i = 0; i < 4000; i++);
    }
}


void USART1_RX_Init(void)
{

    RCC_AHB1ENR |= (1 << 0);


    RCC_APB2ENR |= (1 << 4);


    GPIOA_MODER &= ~(3 << 20);
    GPIOA_MODER |=  (2 << 20);


    GPIOA_AFRH &= ~(0xF << 8);
    GPIOA_AFRH |=  (7 << 8);


    USART1_BRR = 0x0683;


    USART1_CR1 = 0;


    USART1_CR1 |= (1 << 2);


    USART1_CR1 |= (1 << 13);
}


void USART2_TX_Init(void)
{

    RCC_AHB1ENR |= (1 << 0);


    RCC_APB1ENR |= (1 << 17);


    GPIOA_MODER &= ~(3 << 4);
    GPIOA_MODER |=  (2 << 4);


    GPIOA_AFRL &= ~(0xF << 8);
    GPIOA_AFRL |=  (7 << 8);


    USART2_BRR = 0x0683;

    /* Reset CR1 */
    USART2_CR1 = 0;

    /* Transmitter Enable */
    USART2_CR1 |= (1 << 3);

    /* USART Enable */
    USART2_CR1 |= (1 << 13);
}


char USART1_ReadChar(void)
{
    while(!(USART1_SR & (1 << 5)));

    return (char)USART1_DR;
}

void USART2_SendChar(char data)
{
    while(!(USART2_SR & (1 << 7)));

    USART2_DR = data;

    while(!(USART2_SR & (1 << 6)));
}


int main(void)
{
    char data;

    USART1_RX_Init();
    USART2_TX_Init();

    delay_ms(500);

    while(1)
    {
        data = USART1_ReadChar();

        USART2_SendChar(data);
    }
}
