/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_AHB1ENR   (*(volatile uint32_t*)0x40023830)
#define RCC_APB1ENR   (*(volatile uint32_t*)0x40023840)

#define GPIOA_MODER   (*(volatile uint32_t*)0x40020000)
#define GPIOA_AFRL    (*(volatile uint32_t*)0x40020020)

#define USART2_SR     (*(volatile uint32_t*)0x40004400)
#define USART2_DR     (*(volatile uint32_t*)0x40004404)
#define USART2_BRR    (*(volatile uint32_t*)0x40004408)
#define USART2_CR1    (*(volatile uint32_t*)0x4000440C)

void GPIO_Init(void)
{
    RCC_AHB1ENR |= (1 << 0);      //

    // PA2 -> USART2_TX
    GPIOA_MODER &= ~(3 << 4);
    GPIOA_MODER |=  (2 << 4);

    // PA3 -> USART2_RX
    GPIOA_MODER &= ~(3 << 6);
    GPIOA_MODER |=  (2 << 6);

    // AF7 for USART2
    GPIOA_AFRL &= ~(0xF << 8);
    GPIOA_AFRL |=  (7 << 8);

    GPIOA_AFRL &= ~(0xF << 12);
    GPIOA_AFRL |=  (7 << 12);
}

void USART2_Init(void)
{
    RCC_APB1ENR |= (1 << 17);     // USART2 clock enable

    USART2_CR1 = 0;              // Clear control register

    USART2_BRR = 0x008B;         // 115200 baud @ 16MHz

    USART2_CR1 |= (1 << 3);      // TE
    USART2_CR1 |= (1 << 2);      // RE
    USART2_CR1 |= (1 << 13);     // UE
}

void USART2_SendChar(char ch)
{
    while(!(USART2_SR & (1 << 7)));  // Wait TXE

    USART2_DR = ch;

    while(!(USART2_SR & (1 << 6)));  // Wait TC
}

void USART2_SendString(char *str)
{
    while(*str)
    {
        USART2_SendChar(*str++);
    }
}

void delay(void)
{
    for(volatile uint32_t i = 0; i < 10000; i++);
}

int main(void)
{
    GPIO_Init();
    USART2_Init();

    while(1)
    {
        USART2_SendString("CHAITHANYA\r\n");
        delay();
    }
}
